/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bhanu Pratap Singh
 */
public class Interviewer_afterlogin extends javax.swing.JFrame {
public static String mail;
    /**
     * Creates new form Interviewer_afterlogin
     */
    public Interviewer_afterlogin() {
        initComponents();
        
       
    }
   static String ss;
    
  public String mobile,name;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("New Interview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Old Interviews");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(140, 100, 430, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intercode/int700x450.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 450);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Interviewer_working_Area a = new Interviewer_working_Area();
//a.mail = this.mail;
System.out.println("button pressed");
//Interviewer_working_Area i = new Interviewer_working_Area();
//i.port = jTextField1.getText();
System.out.println("object created");
//i.setVisible(true);
String[] args = null;
 Interviewer_working_Area i = new Interviewer_working_Area();
    try {i.setVisible(true);
        i.start();
    } catch (IOException ex) {
        Logger.getLogger(Interviewer_afterlogin.class.getName()).log(Level.SEVERE, null, ex);
    }
 
   // try {
       // Interviewer_working_Area.main(args);
        /**  try {
         * Interviewer_working_Area.main(args);
         * 
         * } catch (IOException ex) {
         * Logger.getLogger(Login_Signup.class.getName()).log(Level.SEVERE, null, ex);
         * }
         * System.out.println("thi  is not visible");
         * this.setVisible(false);
         * //Port_for_new_interview t = new Port_for_new_interview();
         * //t.setVisible(true);
         * // TODO add your handling code here:**/
   // } catch (IOException ex) {
    //    Logger.getLogger(Interviewer_afterlogin.class.getName()).log(Level.SEVERE, null, ex);
  //  } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Login_Signup s = new Login_Signup();
        Interviewer_oldinterviews ssss = new Interviewer_oldinterviews();
        
        System.out.println(ss);
        
        
        
       // Interviewer_oldinterviews o = new Interviewer_oldinterviews();
//this.setVisible(false);
//o.setVisible(true);

Datafetcher1 c =new Datafetcher1();
        try {  c.port = 1203;
            c.fetch("select interviewee,course,branch,marks,comments,interviewee_email,date_time from masterdb where interviewer_email='"+mail+"'");
            System.out.println("query sent...");
            
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Interviewer_afterlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
      ssss.setVisible(true);
        String ss;
        ss = c.get();
       ssss.set(ss);
       
        System.out.println("we get string in current class...");
         
    System.out.println("Constructor called....");
    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interviewer_afterlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interviewer_afterlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interviewer_afterlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interviewer_afterlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interviewer_afterlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
