/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhanu Pratap Singh
 */
public class Interviewee_oldinterviews extends javax.swing.JFrame {
 String a="",b="",s,c="",d="",e="";
   int i=0;
    /**
     * Creates new form Interview_oldinterviews
     */
    public Interviewee_oldinterviews() {
        initComponents();
    }int n=0;
 public void set(String ss){
       System.out.println("MAin const called...");
       s = ss;
        int i;
       for(i=0;i<ss.length();i++)
       {
          if(ss.charAt(i)=='=')
              n++;
       }
       addrowtojtable();
   }
  public void fun()
   {   
       while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       a=a+s.charAt(i++);
      }
        while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       b=b+s.charAt(i++);
      }
         while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       c=c+s.charAt(i++);
      }
          while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       d=d+s.charAt(i++);
      }
         
       
      while(true)
        {
           if(s.charAt(i)=='='  )
              {i++; break;}
           else e=e+s.charAt(i++);
       }
    }
     public void addrowtojtable()
    {    for(int j=0;j<n;j++){  
        
             fun();
        DefaultTableModel model=(DefaultTableModel)tt.getModel();
        model.addRow(new Object[]{a,b,c,d,e});
       a="";b="";c="";d="";e="";
    
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Past Interviews");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jButton1.setText("New Interview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 500, 120, 25);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 510, 120, 25);

        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Interviewer_name", "Interviewer_email", "Interviewer_contact", "Date/Time"
            }
        ));
        jScrollPane2.setViewportView(tt);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 30, 820, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/int880x550.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 560);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Ip_port_for_interviewee p = new Ip_port_for_interviewee();
p.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
Interviewee_afterlogin p = new Interviewee_afterlogin();
p.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interviewee_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interviewee_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interviewee_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interviewee_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interviewee_oldinterviews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tt;
    // End of variables declaration//GEN-END:variables
}
