/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercode;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhanu Pratap Singh
 */
public class Interviewer_oldinterviews extends javax.swing.JFrame {
String a="",b="",s,c="",d="",e="",f="",g="";
   int i=0;
    /**
     * Creates new form Interviewer_oldinterviews
     */
    public Interviewer_oldinterviews() {
        initComponents();
        tt.setEnabled(false);
        
    }  int n=0;
 public void set(String ss){
       System.out.println("MAin const called...");
       s = ss;
       int i;
       for(i=0;i<ss.length();i++)
       {
          if(ss.charAt(i)=='=')
              n++;
       }
       
       addrowtojtable();
   }
    
         
          
    
  
   public void fun()
   {   
       while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       a=a+s.charAt(i++);
      }
        while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       b=b+s.charAt(i++);
      }
         while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       c=c+s.charAt(i++);
      }
          while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       d=d+s.charAt(i++);
      }
           while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       e=e+s.charAt(i++);
      }
       
        while(true)
      {
       if(s.charAt(i)=='!')
       {i++; break;}
       f=f+s.charAt(i++);
      }
        while(true)
        {
           if(s.charAt(i)=='='  )
              {i++; break;}
           else g=g+s.charAt(i++);
       }
    }
     public void addrowtojtable()
    {    for(int j=0;j<n;j++){  
        
             fun();
        DefaultTableModel model=(DefaultTableModel)tt.getModel();
        model.addRow(new Object[]{a,b,c,d,e,f,g});
       a="";b="";c="";d="";e="";f="";g="";
    
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Interviews");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Interviewee_name", "Cource", "Branch", "Marks", "Comments", "Interviewee_no.", "Date/Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tt);
        if (tt.getColumnModel().getColumnCount() > 0) {
            tt.getColumnModel().getColumn(0).setPreferredWidth(25);
            tt.getColumnModel().getColumn(1).setPreferredWidth(30);
            tt.getColumnModel().getColumn(2).setPreferredWidth(15);
            tt.getColumnModel().getColumn(3).setPreferredWidth(10);
            tt.getColumnModel().getColumn(4).setPreferredWidth(20);
            tt.getColumnModel().getColumn(5).setPreferredWidth(50);
            tt.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 840, 470);

        jButton1.setText("New Interview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 500, 140, 25);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 500, 140, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/int880x550.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 550);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Interviewer_afterlogin o = new Interviewer_afterlogin();
o.setVisible(true);
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Port_for_new_interview t = new Port_for_new_interview();
//t.setVisible(true);
  Interviewer_working_Area i = new Interviewer_working_Area();
//i.port = jTextField1.getText();
i.setVisible(true);
this.setVisible(false);    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interviewer_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interviewer_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interviewer_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interviewer_oldinterviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interviewer_oldinterviews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tt;
    // End of variables declaration//GEN-END:variables
}
